name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run Pint
        run: ./vendor/bin/pint --test

  analyse:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse

  test:
    name: Testing
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env.ci
          sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env.ci
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env.ci
          sed -i 's/# DB_PORT=3306/DB_PORT=3306/' .env.ci
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=testing/' .env.ci
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env.ci
          sed -i 's/# DB_PASSWORD=/DB_PASSWORD=password/' .env.ci
          cp .env.ci .env
          php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
